class plt_module(object):

    def __init__(self):
        
        self.dict_event_plt = {
                             'nino' : {
                                       'mean_vmin' : -1.,
                                       'mean_vmax' : 1.,
                                       'std_vmin'  : 0,
                                       'std_vmax'  : 7,
                                      },    
                             'nina' : {
                                       'mean_vmin' : -1.,
                                       'mean_vmax' : 1.,
                                       'std_vmin'  : 0,
                                       'std_vmax'  : 7,
                                      },    
                              }
        self.dict_toy_plt = {
                                 'population' : {
                                                  'color'     : 'k',   
                                                  'linestyle' : '-',
                                                  'linewidth' : 2, 
                                                  'histtype'  : 'stepfilled', 
                                                  'facecolor' : 'b',
                                                  'marker'    : 'x',
                                                  'label'     : '1000-members target',
                                                },
                                 'theoritical' : {
                                                  'color'     : 'k',   
                                                  'linestyle' : 'dotted',
                                                  'linewidth' : 2, 
                                                  'histtype'  : 'stepfilled', 
                                                  'facecolor' : 'b',
                                                  'marker'    : 'x',
                                                  'label'     : 'theoretical',
                                                },
                                 'train_sample' : {
                                                  'color'     : 'k',
                                                  'linestyle' : '--',
                                                  'linewidth' : 2, 
                                                  'histtype'  : 'step',  
                                                  'facecolor' : 'b',
                                                  'marker'    : 'x',
                                                  'label'     : 'Validation',
                                                  },
                                 'toy_VAE1'     : {
                                                  'color'    : 'green',
                                                  'linestyle' : 'dashed',
                                                  'linewidth' : 1, 
                                                  'histtype' : 'step',  
                                                  'facecolor' : 'w',
                                                  'marker'    : 'o',
                                                  'label'     : 'VAE 1$\sigma$',
                                                  },
                                 'toy_VAE2'     : {
                                                  'color'     : 'green',
                                                  'linestyle' : '-',
                                                  'linewidth' : 1.5, 
                                                  'histtype'  : 'step',  
                                                  'facecolor' : 'green',
                                                  'marker'    : 'o',
                                                  'label'     : 'VAE 1.05$\sigma$',
                                                   },
                                 'toy_cVAE1'     : {
                                                  'color'     : 'purple',
                                                  'linestyle' : 'dashed',
                                                  'linewidth' : 1, 
                                                  'histtype'  : 'step',  
                                                  'facecolor' : 'w',
                                                  'marker'    : 'o',
                                                  'label'     : 'cVAE 1$\sigma$',
                                                   },
                                 'toy_cVAE2'     : {
                                                  'color'     : 'purple',
                                                  'linestyle' : '-',
                                                  'linewidth' : 1.5, 
                                                  'histtype'  : 'step',  
                                                  'facecolor' : 'purple',
                                                  'marker'    : 'o',
                                                  'label'     : 'cVAE 1.2$\sigma$',
                                                   }    
                            }        
        self.dict_clm_plt = {
                                 'population' : {
                                                  'color'     : 'k',   
                                                  'label'     : 'population',
                                                  'histtype'  : 'stepfilled',  
                                                  'alpha_hist':  0.5,
                                                  'linestyle' : '-',
                                                  'linewidth' : 2, 
                                                  'facecolor' : 'blue',
                                                  'marker'    : 'x',
                                                  'alpha'     : 1,
                                                  's'         : 80,
                                                },
                                 'train_sample' : {
                                                  'color'     : 'k',
                                                  'linestyle' : 'dashed',
                                                  'linewidth' : 2, 
                                                  'label'     : 'train_sample',
                                                  'histtype'  : 'step',  
                                                  'facecolor' : 'blue',
                                                  'marker'    : 'x',
                                                  'alpha'     : 1,
                                                  's'         : 80,
                                                  },
                                 'clm_VAE1'     : {
                                                  'color'     : 'green',
                                                  'linestyle' : 'dashed',
                                                  'linewidth' : 1, 
                                                  'label'     : 'VAE 1$\sigma$',
                                                  'histtype'  : 'step',  
                                                  'facecolor' : 'w',
                                                  'marker'    : 'o',
                                                  'alpha'     : 0.75,
                                                  },
                                 'clm_VAE1_'     : {
                                                  'color'     : 'green',
                                                  'linestyle' : 'dashed',
                                                  'linewidth' : 1, 
                                                  'label'     : 'VAE 1$\sigma$ MSE equalweight',
                                                  'histtype'  : 'step',  
                                                  'facecolor' : 'w',
                                                  'marker'    : 'o',
                                                  'alpha'     : 0.5,
                                                  },
                                 'clm_VAE2'     : {
                                                  'color'     : 'green',
                                                  'linestyle' : 'dotted',
                                                  'linewidth' : 1, 
                                                  'label'     : 'VAE 1.6$\sigma$',
                                                  'histtype'  : 'step',  
                                                  'facecolor' : 'green',
                                                  'alpha'     : 0.5,
                                                  'marker'    : 'o',
                                                  },
                                 'clm_VAE3'     : {
                                                  'color'     : 'green',
                                                  'linestyle' : '-',
                                                  'linewidth' : 1, 
                                                  'label'     : 'VAE 1.3$\sigma + DN$',
                                                  'histtype'  : 'step',  
                                                  'facecolor' : 'green',
                                                  'marker'    : 'o',
                                                  'alpha'     : 1,
                                                  },

                                 'clm_VAE3_'     : {
                                                  'color'     : 'green',
                                                  'linestyle' : '-.',
                                                  'linewidth' : 1, 
                                                  'label'     : 'VAE 1.3$\sigma$',
                                                  'histtype'  : 'step',  
                                                  'facecolor' : 'w',
                                                  'marker'    : 'o',
                                                  'alpha'     : 0.5,
                                                  },
                                 'clm_cVAE1'     : {
                                                  'color'     : 'purple',
                                                  'linestyle' : 'dashed',
                                                  'linewidth' : 1, 
                                                  'label'     : 'cVAE 1$\sigma$',
                                                  'histtype'  : 'step',  
                                                  'facecolor' : 'w',
                                                  'marker'    : 'o',
                                                  'alpha'     : 0.75,
                                                   },
                                 'clm_cVAE2'     : {
                                                  'color'     : 'purple',
                                                  'linestyle' : 'dotted',
                                                  'linewidth' : 1, 
                                                  'label'     : 'cVAE 1$\sigma + DN$',
                                                  'histtype'  : 'step',  
                                                  'facecolor' : 'purple',
                                                  'marker'    : 'o',
                                                  'alpha'     : 0.5,
                                                   },
                                 'clm_cVAE3'     : {
                                                  'color'     : 'purple',
                                                  'linestyle' : '-',
                                                  'linewidth' : 1, 
                                                  'label'     : 'CC-cVAE 1$\sigma + DN$',
                                                  'histtype'  : 'step',  
                                                  'facecolor' : 'purple',
                                                  'marker'    : 'o',
                                                  'alpha'     : 1,
                                                   },    
                            }